### ISSUE TITLE
Responsive "Cancel" and "Save" buttons doesn't work

### ISSUE THREAD

**Issue by halupi** [mrdannael/angular-material-datepicker#2]
Hi! it's me again lol. Well I was testing your calendar on responsive mode and I got the following errors:
  1. Cancel and Save texts didn't change
  2. Both buttons doesn't work at click. 

I got this on console
![screen shot 2015-10-30 at 6 47 44 pm](https://cloud.githubusercontent.com/assets/13356194/10860938/bdc5ae40-7f36-11e5-81c6-ab82d26f4e45.png)

and this is how texts doesn't change
NORMAL => ![screen shot 2015-10-30 at 6 49 46 pm](https://cloud.githubusercontent.com/assets/13356194/10860953/18f87540-7f37-11e5-9416-ccd23e4e1d7d.png)
RESPONSIVE = > ![screen shot 2015-10-30 at 6 49 55 pm](https://cloud.githubusercontent.com/assets/13356194/10860954/1a55c4c4-7f37-11e5-83ad-e3995e7d4b73.png)

Thanks!

**Comment by mrdannael** [comment]
Thanks for info again, lol. I'll fix that soon and let you know.

**Comment by mrdannael** [comment]
@halupi problem solved. Datepicker updated. Thanks again.
